name: shia_companion
description: A new Flutter project.

version: 2.9.1+50

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  auth_buttons: ^3.0.0
  csv: ^5.0.2
  date_format: ^2.0.7
  firebase_auth: ^4.6.0
  firebase_crashlytics: ^3.3.0
  firebase_database: ^10.2.0
  flutter_beep: ^1.0.0
  flutter_local_notifications: ^14.0.0+2
  geocoding: ^2.1.0
  hijri: ^3.0.0
  location: ^5.0.1
  package_info: ^2.0.2
  share_plus: ^6.3.4
  shared_preferences: ^2.1.1
  table_calendar: ^3.0.9
  url_launcher: ^6.1.11
  wakelock: ^0.6.2
  webfeed_revised: ^0.7.2
  yaml: ^3.1.2
  flutter_markdown: ^0.6.17
  flutter_webview_plugin: ^0.4.0
  intl: ^0.18.1
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.1.4
  flutter_timezone: ^1.0.7
  timezone: ^0.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/zikr/
    - assets/hadith.csv
    - assets/items/

  fonts:
    - family: Qalam
      fonts:
        - asset: assets/fonts/qalam
    - family: MeQuran
      fonts:
        - asset: assets/fonts/me_quran.ttf
  #  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

