name: shia_companion
description: A new Flutter project.

version: 2.0+2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_database: ^4.0.0
  google_sign_in: ^4.5.4
  flutter_auth_buttons: ^0.10.0
  flutter_native_timezone: ^1.0.4
  location: ^3.0.2
  http: ^0.12.2
  shared_preferences: ^0.5.10
  flutter_webview_plugin: ^0.3.11
  url_launcher: ^5.5.3
  hijri: ^2.0.3
  date_format: ^1.0.8
  csv: ^4.0.3
  firebase_crashlytics: ^0.2.1+1
  flutter_local_notifications: ^1.4.4+4
  table_calendar: ^2.2.3
  share: ^0.6.5
  package_info: ^0.4.3
  apple_sign_in: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/zikr/
    - assets/hadith.csv

  fonts:
    - family: Qalam
      fonts:
        - asset: assets/fonts/qalam
    - family: MeQuran
      fonts:
        - asset: assets/fonts/me_quran.ttf
  #  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

