name: shia_companion
description: A new Flutter project.

version: 3.0+45

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_timezone: ^1.0.4
  location: ^2.3.5
  http: ^0.12.0
  shared_preferences: ^0.5.6
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.10
  url_launcher: ^5.2.5
  firebase_analytics: ^5.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/logo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/hadiths/

  fonts:
    - family: Qalam
      fonts:
        - asset: assets/fonts/qalam
  #  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
