name: shia_companion
description: A new Flutter project.

version: 2.7.0+48

environment:
  sdk: ^3.0.0

dependencies:
  provider: ^6.0.5
  adhan_dart: ^1.0.8
  auth_buttons: ^3.0.0
  csv: ^5.0.2
  date_format: ^2.0.7
  firebase_auth: ^4.6.0
  firebase_crashlytics: ^3.3.0
  firebase_database: ^10.2.0
  flutter:
    sdk: flutter
  flutter_beep: ^1.0.0
  flutter_local_notifications: ^14.0.0+2
  geocoding: ^2.1.0
  hijri: ^3.0.0
  location: ^5.0.1
  package_info: ^2.0.2
  share_plus: ^6.3.4
  shared_preferences: ^2.1.1
  sign_in_with_apple: ^4.3.0
  table_calendar: ^3.0.9
  url_launcher: ^6.1.11
  wakelock: ^0.6.2
  webview_flutter: ^4.2.0
  webfeed_revised: ^0.7.2
  yaml: ^3.1.2
  flutter_markdown: ^0.6.17
  flutter_webview_plugin: ^0.4.0
  intl: ^0.18.1
  the_apple_sign_in: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
# dependency_overrides:
#   screenshots:
#     git: https://github.com/trygvis/screenshots
#   tool_base:
#     git: https://github.com/speaking-in-code/tool_base
#   tool_base_test:
#     git: https://github.com/trygvis/tool_base_test
#   tool_mobile:
#     git: https://github.com/trygvis/tool_mobile
#   fake_process_manager:
#     git: https://github.com/trygvis/fake_process_manager

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/zikr/
    - assets/hadith.csv
    - assets/items/

  fonts:
    - family: Qalam
      fonts:
        - asset: assets/fonts/qalam
    - family: MeQuran
      fonts:
        - asset: assets/fonts/me_quran.ttf
  #  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

